services:
  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend-java

  backend-java:
    build:
      context: ./backend/java/db-search-assistant/db-search-assistant
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

volumes:
  postgres_data: